"""Core, transport-independent domain models and algorithms."""

from aegis_cartographer.core.exploration import (
    ExplorationBudget,
    ExplorationEngine,
    ExplorationRunStore,
    ExplorationStatus,
    ExplorationTask,
    ExplorationTaskStatus,
    SafetyPolicy,
)
from aegis_cartographer.core.hierarchy import (
    HierarchyValidationError,
    NormalizedHierarchy,
    UiElement,
    compute_screen_signature,
    extract_ui_elements,
    normalize_hierarchy,
    parse_bounds,
)
from aegis_cartographer.core.identity import (
    ScreenMatcher,
    create_state_record,
    derive_screen_id,
    derive_state_id,
    observe_screen,
)
from aegis_cartographer.core.models import (
    Bounds,
    CandidateScore,
    NormalizedNode,
    Platform,
    ScreenMatchResult,
    ScreenMatchType,
    ScreenObservation,
    ScreenSignature,
    ScreenStateRecord,
    ScreenStateType,
)
from aegis_cartographer.core.query import (
    ElementQueryResult,
    MapPathExecutor,
    MapQueryService,
    PathExecutionResult,
    PathPlan,
    ScreenQueryResult,
    render_maestro_flow,
)
from aegis_cartographer.core.storage import (
    MapId,
    MapStore,
    ProjectWorkspace,
)

__all__ = [
    "ElementQueryResult",
    "ExplorationBudget",
    "ExplorationEngine",
    "ExplorationRunStore",
    "ExplorationStatus",
    "ExplorationTask",
    "ExplorationTaskStatus",
    "SafetyPolicy",
    "Bounds",
    "CandidateScore",
    "MapQueryService",
    "MapPathExecutor",
    "PathExecutionResult",
    "PathPlan",
    "HierarchyValidationError",
    "NormalizedHierarchy",
    "NormalizedNode",
    "Platform",
    "ScreenMatchResult",
    "ScreenMatchType",
    "ScreenObservation",
    "ScreenStateRecord",
    "ScreenStateType",
    "ScreenSignature",
    "ScreenMatcher",
    "ScreenQueryResult",
    "MapId",
    "MapStore",
    "ProjectWorkspace",
    "create_state_record",
    "derive_screen_id",
    "derive_state_id",
    "observe_screen",
    "UiElement",
    "compute_screen_signature",
    "extract_ui_elements",
    "normalize_hierarchy",
    "parse_bounds",
    "render_maestro_flow",
]
